SummaryInd$flower_inv <-SummaryInd$prepollencosts*SummaryInd$repro_all_count
SummaryInd$percent_for_seeds <- SummaryInd$propagule_inv / SummaryInd$repro_inv
mod <- sma(percent_to_seeds~seed_size,data=subset(SummaryInd,percent_to_seeds>0),log="xy")
summary(mod)

plot(percent_for_success~seed_size,SummaryInd,pch=16,log="xy",col=col.spp(species))
mod <- sma(percent_for_success~seed_size,data=subset(SummaryInd,percent_for_success>0),method="OLS", log="xy")
abline(mod$coef[[1]][1,1],mod$coef[[1]][2,1])

plot(percent_for_seeds~seed_size,SummaryInd,pch=16,log="xy",col=col.spp(species))
mod <- sma(percent_for_seeds~seed_size,data=subset(SummaryInd,percent_for_seeds>0),method="OLS", log="xy")
abline(mod$coef[[1]][1,1],mod$coef[[1]][2,1])

```{r}
#as seed size increases, the cost of making an additional flower decreases
plot(prepollencosts~seed_size,SummaryInd,pch=16,log="xy",col=col.spp(species),xlim=c(1e-3,1e2),ylim=c(1e-3,1e2))
mod <- sma(prepollencosts~seed_size,data=subset(SummaryInd,prepollencosts>0),method="OLS", log="xy",slope=1)
abline(mod$coef[[1]][1,1],mod$coef[[1]][2,1])
summary(mod)
abline(0,1,col="red")

plot(repro_inv~seed_size,SummaryInd,pch=16,log="xy",col=col.spp(species),xlim=c(1e-3,1e2))
mod <- sma(repro_inv~seedcosts,data=subset(SummaryInd,repro_inv>0),method="OLS", log="xy",slope=1)
abline(mod$coef[[1]][1,1],mod$coef[[1]][2,1])
summary(mod)
abline(0,1,col="red")
```



```{r}
mod <- sma(total_weight~repro_inv,data=subset(SummaryInd,repro_inv>0),log="xy",method="OLS", slope=1)
Table_best_corr <- as.data.frame("total plant weight")
Table_best_corr <- bind_cols(Table_best_corr,as.data.frame(mod$r2[[1]]),as.data.frame(mod$pval[[1]]),as.data.frame(mod$coef[[1]][1,1]),
                             as.data.frame(mod$coef[[1]][2,1]),as.data.frame(mod$coef[[1]][2,2]),as.data.frame(mod$coef[[1]][2,3]))
names(Table_best_corr) <- c("investment category (mg)","r squared","p value","intercept","slope","slope_min","slope_max")

mod <- sma(costs_for_failure~repro_inv,data=subset(SummaryInd,costs_for_failure>0),log="xy",method="OLS", slope=1)
new_row <- as.data.frame("failed tissues")
new_row <- bind_cols(new_row,as.data.frame(mod$r2[[1]]),as.data.frame(mod$pval[[1]]),as.data.frame(mod$coef[[1]][1,1]),
                     as.data.frame(mod$coef[[1]][2,1]),as.data.frame(mod$coef[[1]][2,2]),as.data.frame(mod$coef[[1]][2,3]))
names(new_row) <- c("investment category (mg)","r squared","p value","intercept","slope","slope_min","slope_max")
Table_best_corr <- bind_rows(Table_best_corr,new_row)

mod <- sma(costs_for_success~repro_inv,data=subset(SummaryInd,costs_for_success>0),log="xy",method="OLS", slope=1)
new_row <- as.data.frame("successful tissues")
new_row <- bind_cols(new_row,as.data.frame(mod$r2[[1]]),as.data.frame(mod$pval[[1]]),as.data.frame(mod$coef[[1]][1,1]),
                     as.data.frame(mod$coef[[1]][2,1]),as.data.frame(mod$coef[[1]][2,2]),as.data.frame(mod$coef[[1]][2,3]))
names(new_row) <- c("investment category (mg)","r squared","p value","intercept","slope","slope_min","slope_max")
Table_best_corr <- bind_rows(Table_best_corr,new_row)

mod <- sma(prepollen_required_inv~repro_inv,data=subset(SummaryInd,prepollen_required_inv>0),log="xy",method="OLS", slope=1)
new_row <- as.data.frame("prepollen_required_investment")
new_row <- bind_cols(new_row,as.data.frame(mod$r2[[1]]),as.data.frame(mod$pval[[1]]),as.data.frame(mod$coef[[1]][1,1]),
                     as.data.frame(mod$coef[[1]][2,1]),as.data.frame(mod$coef[[1]][2,2]),as.data.frame(mod$coef[[1]][2,3]))
names(new_row) <- c("investment category (mg)","r squared","p value","intercept","slope","slope_min","slope_max")
Table_best_corr <- bind_rows(Table_best_corr,new_row)

mod <- sma(packaging_dispersal_inv~repro_inv,data=subset(SummaryInd,packaging_dispersal_inv>0),log="xy",method="OLS", slope=1)
new_row <- as.data.frame("packaging&dispersal")
new_row <- bind_cols(new_row,as.data.frame(mod$r2[[1]]),as.data.frame(mod$pval[[1]]),as.data.frame(mod$coef[[1]][1,1]),
                     as.data.frame(mod$coef[[1]][2,1]),as.data.frame(mod$coef[[1]][2,2]),as.data.frame(mod$coef[[1]][2,3]))
names(new_row) <- c("investment category (mg)","r squared","p value","intercept","slope","slope_min","slope_max")
Table_best_corr <- bind_rows(Table_best_corr,new_row)

mod <- sma(propagule_inv~repro_inv,data=subset(SummaryInd,propagule_inv>0),log="xy",method="OLS", slope=1)
new_row <- as.data.frame("propagule")
new_row <- bind_cols(new_row,as.data.frame(mod$r2[[1]]),as.data.frame(mod$pval[[1]]),as.data.frame(mod$coef[[1]][1,1]),
                     as.data.frame(mod$coef[[1]][2,1]),as.data.frame(mod$coef[[1]][2,2]),as.data.frame(mod$coef[[1]][2,3]))
names(new_row) <- c("investment category (mg)","r squared","p value","intercept","slope","slope_min","slope_max")
Table_best_corr <- bind_rows(Table_best_corr,new_row)

mod <- sma(fruit_weight~repro_inv,data=subset(SummaryInd,fruit_weight>0),log="xy",method="OLS", slope=1)
new_row <- as.data.frame("fruit")
new_row <- bind_cols(new_row,as.data.frame(mod$r2[[1]]),as.data.frame(mod$pval[[1]]),as.data.frame(mod$coef[[1]][1,1]),
                     as.data.frame(mod$coef[[1]][2,1]),as.data.frame(mod$coef[[1]][2,2]),as.data.frame(mod$coef[[1]][2,3]))
names(new_row) <- c("investment category (mg)","r squared","p value","intercept","slope","slope_min","slope_max")
Table_best_corr <- bind_rows(Table_best_corr,new_row)

mod <- sma(prepollen_all_inv~repro_inv,data=subset(SummaryInd,prepollen_all_inv>0),log="xy",method="OLS", slope=1)
new_row <- as.data.frame("all prepollination tissues")
new_row <- bind_cols(new_row,as.data.frame(mod$r2[[1]]),as.data.frame(mod$pval[[1]]),as.data.frame(mod$coef[[1]][1,1]),
                     as.data.frame(mod$coef[[1]][2,1]),as.data.frame(mod$coef[[1]][2,2]),as.data.frame(mod$coef[[1]][2,3]))
names(new_row) <- c("investment category (mg)","r squared","p value","intercept","slope","slope_min","slope_max")
Table_best_corr <- bind_rows(Table_best_corr,new_row)

mod <- sma(flower_inv~repro_inv,data=subset(SummaryInd,flower_inv>0),log="xy",method="OLS", slope=1)
new_row <- as.data.frame("flower weight * buds initiated")
new_row <- bind_cols(new_row,as.data.frame(mod$r2[[1]]),as.data.frame(mod$pval[[1]]),as.data.frame(mod$coef[[1]][1,1]),
                     as.data.frame(mod$coef[[1]][2,1]),as.data.frame(mod$coef[[1]][2,2]),as.data.frame(mod$coef[[1]][2,3]))
names(new_row) <- c("investment category (mg)","r squared","p value","intercept","slope","slope_min","slope_max")
Table_best_corr <- bind_rows(Table_best_corr,new_row)
```