check <- SummaryInd
check$repro_inv2 <- check$packaging_dispersal_inv + check$postpollen_aborted_inv + check$prepollen_inv_aborted_preflowering + prepollen_inv_reach_flowering + check$propagule_inv

repro_check <- InvestmentByPart %>%
  group_by(individual) %>%
  summarise_each(funs(sum), weight)

library(dplyr)

check <- join(check,repro_check,by="individual")
plot(repro_inv~weight,check,col=col.spp(species),log="xy",pch=16)
check$diff <-check$repro_inv-check$weight


plot(diff~leaf_area_0,check,col=col.spp(species),log="x",pch=16)



check <- select(SummaryInd,individual,species, prepollen_inv_from_dispersal, seed_count,pack_disp_early_costs)
check$costs2 <- check$prepollen_inv_from_dispersal/check$seed_count
plot(costs2~pack_disp_early_costs,check,col=col.spp(species),pch=16,log="xy")
abline(0,1)

check <- subset(InvestmentByPart,species=="BAER")
unique(check$part)

part_check <- check %>%
  group_by(part) %>%
  summarise_each(funs(sum), weight)

View(part_check)

unique(part_check$part)
  
check <-subset(SummaryInd,species=="BAER")
check<-select(check,seed_count,individual)
names(SummaryInd)


SummaryInd$seed_count
```
check2 <- select(SummaryInd,individual,species,seed_count,seed_early_costs,prepollen_inv_from_propagule)
check2 <- subset(check2,seed_count>0)

check2$costs2 <- check2$prepollen_inv_from_propagule/check2$seed_count
plot(costs2~seed_early_costs,check2,col=col.spp(species),pch=16,log="xy")

check <- subset(InvestmentByPart,part=="seed"|part=="fruit_mature")

part_check <- check %>%
  group_by(part,individual) %>%
  summarise_each(funs(sum), weight,count)

part_check$unit_weight <-part_check$weight/part_check$count

check3 <- join(part_check,check2,by="individual")

```
names(check2)

check_COER <- subset(InvestmentByPart,species=="PUTU"&(part=="seed"|part=="")

part_check <- check_COER %>%
  group_by(individual) %>%
  summarise_each(funs(sum), weight,count)

check4 <- subset(SummaryInd,species=="COER"&seed_count>0)
check4 <- select(check4,individual,seed_count)

check <- subset(PartsSummary,species=="GRSP"&(part=="flower_stigma"|part=="finished_flower_stigma"))


plot(prepollen_inv_from_propagule_all ~ prepollen_prop_v2,SummaryInd,col=col.spp(species),pch=16,log="xy")
SummaryInd$prepollen_inv_from_propagule_all



```{r}
par(mfrow=c(1,1), cex=1, omi=c(.1,.1,.05,.05), mai=c(.8,.8,.1,.05)) 
repro3 <- InvestmentByPart %>%
    group_by(individual) %>%
    summarise_each(funs(sum), weight)

SummaryInd$repro_new <- SummaryInd$prepollen2_all_inv + SummaryInd$postpollen2_all_inv
repro4 <- select(SummaryInd,individual,seed_count,repro_inv,repro_new, species)
repro4 <- merge(repro4,repro3,by="individual")
plot(weight ~ repro_new,repro4,col=col.spp(species),pch=16,log="xy")
abline(0,1)

repro5 <- subset(repro4,repro_inv!=weight)
plot(weight ~ repro_inv,repro5,col=col.spp(species),pch=16,log="xy")
```

plot(required_inv2 ~ required_inv,SummaryInd,col=col.spp(species),pch=16,log="xy")
abline(0,1)


plot(seed_costs ~ seed_costs2,SummaryInd,col=col.spp(species),pch=16,log="xy")
abline(0,1)

#works
SummaryInd$success <- SummaryInd$pollen_attract_costs*SummaryInd$seed_count
plot(prepollen_success_inv ~ success,SummaryInd,col=col.spp(species),pch=16,log="xy")
abline(0,1)

#works
SummaryInd$propagule <- SummaryInd$propagule_costs*SummaryInd$seed_count
plot(propagule_inv ~ propagule,SummaryInd,col=col.spp(species),pch=16,log="xy")
abline(0,1)

SummaryInd$propagule <- SummaryInd$propagule_costs*SummaryInd$seed_count
plot(propagule_inv ~ propagule,SummaryInd,col=col.spp(species),pch=16,log="xy")
abline(0,1)



part=="flower_petals"|part=="late_flower_petals"|

check <- subset(InvestmentByPart,species=="BOLE"&(part=="finished_flower"|part=="flower_petals"))
check

check <- subset(InvestmentByPart,species=="BAER"&(part=="seed"|part=="seed_pod"))
check2 <- subset(PartsSummary,part=="flower_stigma"|part=="finished_flower_stigma")
check1 <- subset(PartsSummary,part=="seed"|part=="fruit_mature")
check1 <- merge(check1,check2,by="species")
check1$ratio <- check1$weight.y/check1$weight.x
check1$complement <- 1 - check1$ratio
check1 <- check1[]


check2 <- subset(InvestmentByPart,species=="BOLE"&(part=="late_flower_petals"|part=="flower_petals"))

repro3 <- check2 %>%
    group_by(individual) %>%
    summarise_each(funs(sum), count)

check <- subset(SummaryInd,species=="BOLE")
check <- select(check,individual, postpollen_count,prepollen_count_reach_flowering,seed_count)
check3 <- merge(check,repro3,by="individual")

InvCat <- InvestmentCategories[["BOLE"]]
InvCat <- InvestmentCategories[["COER"]]
InvCat <- InvestmentCategories[["EPMI"]]
InvCat <- InvestmentCategories[["GRBU"]]
InvCat <- InvestmentCategories[["GRSP"]]
InvCat <- InvestmentCategories[["HATE"]]
InvCat <- InvestmentCategories[["HEPU"]]
InvCat <- InvestmentCategories[["LEES"]]
InvCat <- InvestmentCategories[["PELA"]]
InvCat <- InvestmentCategories[["PEPU"]]
InvCat <- InvestmentCategories[["PHPH"]]
InvCat <- InvestmentCategories[["PILI"]]
InvCat <- InvestmentCategories[["PUTU"]]
