# This file is automatically generated from maker_data.yml.whisker:
# edit the file there (or the files that it includes).

filterToBAER <- function(...){
	filterBySpecies("BAER", ...)
}

CalculateInvestmentForBAER <- function(...) {
	CalculateInvestmentForSpecies("BAER", ...)
}

CalculateAccesoryCostsForBAER <- function(...) {
	IAT_Species("BAER", ...)
}

CalculateRAForBAER <- function(...) {
	RA_Calculations("BAER", ...)
}

print_xtable_BAER <- function(...) {
	print_xtable_for_species("BAER", ...)
}

filterToBOLE <- function(...){
	filterBySpecies("BOLE", ...)
}

CalculateInvestmentForBOLE <- function(...) {
	CalculateInvestmentForSpecies("BOLE", ...)
}

CalculateAccesoryCostsForBOLE <- function(...) {
	IAT_Species("BOLE", ...)
}

CalculateRAForBOLE <- function(...) {
	RA_Calculations("BOLE", ...)
}

print_xtable_BOLE <- function(...) {
	print_xtable_for_species("BOLE", ...)
}

filterToCOER <- function(...){
	filterBySpecies("COER", ...)
}

CalculateInvestmentForCOER <- function(...) {
	CalculateInvestmentForSpecies("COER", ...)
}

CalculateAccesoryCostsForCOER <- function(...) {
	IAT_Species("COER", ...)
}

CalculateRAForCOER <- function(...) {
	RA_Calculations("COER", ...)
}

print_xtable_COER <- function(...) {
	print_xtable_for_species("COER", ...)
}

filterToEPMI <- function(...){
	filterBySpecies("EPMI", ...)
}

CalculateInvestmentForEPMI <- function(...) {
	CalculateInvestmentForSpecies("EPMI", ...)
}

CalculateAccesoryCostsForEPMI <- function(...) {
	IAT_Species("EPMI", ...)
}

CalculateRAForEPMI <- function(...) {
	RA_Calculations("EPMI", ...)
}

print_xtable_EPMI <- function(...) {
	print_xtable_for_species("EPMI", ...)
}

filterToGRBU <- function(...){
	filterBySpecies("GRBU", ...)
}

CalculateInvestmentForGRBU <- function(...) {
	CalculateInvestmentForSpecies("GRBU", ...)
}

CalculateAccesoryCostsForGRBU <- function(...) {
	IAT_Species("GRBU", ...)
}

CalculateRAForGRBU <- function(...) {
	RA_Calculations("GRBU", ...)
}

print_xtable_GRBU <- function(...) {
	print_xtable_for_species("GRBU", ...)
}

filterToGRSP <- function(...){
	filterBySpecies("GRSP", ...)
}

CalculateInvestmentForGRSP <- function(...) {
	CalculateInvestmentForSpecies("GRSP", ...)
}

CalculateAccesoryCostsForGRSP <- function(...) {
	IAT_Species("GRSP", ...)
}

CalculateRAForGRSP <- function(...) {
	RA_Calculations("GRSP", ...)
}

print_xtable_GRSP <- function(...) {
	print_xtable_for_species("GRSP", ...)
}

filterToHATE <- function(...){
	filterBySpecies("HATE", ...)
}

CalculateInvestmentForHATE <- function(...) {
	CalculateInvestmentForSpecies("HATE", ...)
}

CalculateAccesoryCostsForHATE <- function(...) {
	IAT_Species("HATE", ...)
}

CalculateRAForHATE <- function(...) {
	RA_Calculations("HATE", ...)
}

print_xtable_HATE <- function(...) {
	print_xtable_for_species("HATE", ...)
}

filterToHEPU <- function(...){
	filterBySpecies("HEPU", ...)
}

CalculateInvestmentForHEPU <- function(...) {
	CalculateInvestmentForSpecies("HEPU", ...)
}

CalculateAccesoryCostsForHEPU <- function(...) {
	IAT_Species("HEPU", ...)
}

CalculateRAForHEPU <- function(...) {
	RA_Calculations("HEPU", ...)
}

print_xtable_HEPU <- function(...) {
	print_xtable_for_species("HEPU", ...)
}

filterToLEES <- function(...){
	filterBySpecies("LEES", ...)
}

CalculateInvestmentForLEES <- function(...) {
	CalculateInvestmentForSpecies("LEES", ...)
}

CalculateAccesoryCostsForLEES <- function(...) {
	IAT_Species("LEES", ...)
}

CalculateRAForLEES <- function(...) {
	RA_Calculations("LEES", ...)
}

print_xtable_LEES <- function(...) {
	print_xtable_for_species("LEES", ...)
}

filterToPELA <- function(...){
	filterBySpecies("PELA", ...)
}

CalculateInvestmentForPELA <- function(...) {
	CalculateInvestmentForSpecies("PELA", ...)
}

CalculateAccesoryCostsForPELA <- function(...) {
	IAT_Species("PELA", ...)
}

CalculateRAForPELA <- function(...) {
	RA_Calculations("PELA", ...)
}

print_xtable_PELA <- function(...) {
	print_xtable_for_species("PELA", ...)
}

filterToPEPU <- function(...){
	filterBySpecies("PEPU", ...)
}

CalculateInvestmentForPEPU <- function(...) {
	CalculateInvestmentForSpecies("PEPU", ...)
}

CalculateAccesoryCostsForPEPU <- function(...) {
	IAT_Species("PEPU", ...)
}

CalculateRAForPEPU <- function(...) {
	RA_Calculations("PEPU", ...)
}

print_xtable_PEPU <- function(...) {
	print_xtable_for_species("PEPU", ...)
}

filterToPHPH <- function(...){
	filterBySpecies("PHPH", ...)
}

CalculateInvestmentForPHPH <- function(...) {
	CalculateInvestmentForSpecies("PHPH", ...)
}

CalculateAccesoryCostsForPHPH <- function(...) {
	IAT_Species("PHPH", ...)
}

CalculateRAForPHPH <- function(...) {
	RA_Calculations("PHPH", ...)
}

print_xtable_PHPH <- function(...) {
	print_xtable_for_species("PHPH", ...)
}

filterToPILI <- function(...){
	filterBySpecies("PILI", ...)
}

CalculateInvestmentForPILI <- function(...) {
	CalculateInvestmentForSpecies("PILI", ...)
}

CalculateAccesoryCostsForPILI <- function(...) {
	IAT_Species("PILI", ...)
}

CalculateRAForPILI <- function(...) {
	RA_Calculations("PILI", ...)
}

print_xtable_PILI <- function(...) {
	print_xtable_for_species("PILI", ...)
}

filterToPUTU <- function(...){
	filterBySpecies("PUTU", ...)
}

CalculateInvestmentForPUTU <- function(...) {
	CalculateInvestmentForSpecies("PUTU", ...)
}

CalculateAccesoryCostsForPUTU <- function(...) {
	IAT_Species("PUTU", ...)
}

CalculateRAForPUTU <- function(...) {
	RA_Calculations("PUTU", ...)
}

print_xtable_PUTU <- function(...) {
	print_xtable_for_species("PUTU", ...)
}


