# This file is automatically generated from maker_data.yml.whisker:
# edit the file there (or the files that it includes).

make_HarvestDataForBAER <- function(...){
	filterBySpecies("BAER", ...)
}

CalculateInvestmentForBAER <- function(...) {
	CalculateInvestmentForSpecies("BAER", ...)
}

CalculateAccesoryCostsForBAER <- function(...) {
	IAT_Species("BAER", ...)
}

CalculateRAForBAER <- function(...) {
	RA_Calculations("BAER", ...)
}

make_HarvestDataForBOLE <- function(...){
	filterBySpecies("BOLE", ...)
}

CalculateInvestmentForBOLE <- function(...) {
	CalculateInvestmentForSpecies("BOLE", ...)
}

CalculateAccesoryCostsForBOLE <- function(...) {
	IAT_Species("BOLE", ...)
}

CalculateRAForBOLE <- function(...) {
	RA_Calculations("BOLE", ...)
}

make_HarvestDataForCOER <- function(...){
	filterBySpecies("COER", ...)
}

CalculateInvestmentForCOER <- function(...) {
	CalculateInvestmentForSpecies("COER", ...)
}

CalculateAccesoryCostsForCOER <- function(...) {
	IAT_Species("COER", ...)
}

CalculateRAForCOER <- function(...) {
	RA_Calculations("COER", ...)
}

make_HarvestDataForEPMI <- function(...){
	filterBySpecies("EPMI", ...)
}

CalculateInvestmentForEPMI <- function(...) {
	CalculateInvestmentForSpecies("EPMI", ...)
}

CalculateAccesoryCostsForEPMI <- function(...) {
	IAT_Species("EPMI", ...)
}

CalculateRAForEPMI <- function(...) {
	RA_Calculations("EPMI", ...)
}

make_HarvestDataForGRBU <- function(...){
	filterBySpecies("GRBU", ...)
}

CalculateInvestmentForGRBU <- function(...) {
	CalculateInvestmentForSpecies("GRBU", ...)
}

CalculateAccesoryCostsForGRBU <- function(...) {
	IAT_Species("GRBU", ...)
}

CalculateRAForGRBU <- function(...) {
	RA_Calculations("GRBU", ...)
}

make_HarvestDataForGRSP <- function(...){
	filterBySpecies("GRSP", ...)
}

CalculateInvestmentForGRSP <- function(...) {
	CalculateInvestmentForSpecies("GRSP", ...)
}

CalculateAccesoryCostsForGRSP <- function(...) {
	IAT_Species("GRSP", ...)
}

CalculateRAForGRSP <- function(...) {
	RA_Calculations("GRSP", ...)
}

make_HarvestDataForHATE <- function(...){
	filterBySpecies("HATE", ...)
}

CalculateInvestmentForHATE <- function(...) {
	CalculateInvestmentForSpecies("HATE", ...)
}

CalculateAccesoryCostsForHATE <- function(...) {
	IAT_Species("HATE", ...)
}

CalculateRAForHATE <- function(...) {
	RA_Calculations("HATE", ...)
}

make_HarvestDataForHEPU <- function(...){
	filterBySpecies("HEPU", ...)
}

CalculateInvestmentForHEPU <- function(...) {
	CalculateInvestmentForSpecies("HEPU", ...)
}

CalculateAccesoryCostsForHEPU <- function(...) {
	IAT_Species("HEPU", ...)
}

CalculateRAForHEPU <- function(...) {
	RA_Calculations("HEPU", ...)
}

make_HarvestDataForLEES <- function(...){
	filterBySpecies("LEES", ...)
}

CalculateInvestmentForLEES <- function(...) {
	CalculateInvestmentForSpecies("LEES", ...)
}

CalculateAccesoryCostsForLEES <- function(...) {
	IAT_Species("LEES", ...)
}

CalculateRAForLEES <- function(...) {
	RA_Calculations("LEES", ...)
}

make_HarvestDataForPELA <- function(...){
	filterBySpecies("PELA", ...)
}

CalculateInvestmentForPELA <- function(...) {
	CalculateInvestmentForSpecies("PELA", ...)
}

CalculateAccesoryCostsForPELA <- function(...) {
	IAT_Species("PELA", ...)
}

CalculateRAForPELA <- function(...) {
	RA_Calculations("PELA", ...)
}

make_HarvestDataForPEPU <- function(...){
	filterBySpecies("PEPU", ...)
}

CalculateInvestmentForPEPU <- function(...) {
	CalculateInvestmentForSpecies("PEPU", ...)
}

CalculateAccesoryCostsForPEPU <- function(...) {
	IAT_Species("PEPU", ...)
}

CalculateRAForPEPU <- function(...) {
	RA_Calculations("PEPU", ...)
}

make_HarvestDataForPHPH <- function(...){
	filterBySpecies("PHPH", ...)
}

CalculateInvestmentForPHPH <- function(...) {
	CalculateInvestmentForSpecies("PHPH", ...)
}

CalculateAccesoryCostsForPHPH <- function(...) {
	IAT_Species("PHPH", ...)
}

CalculateRAForPHPH <- function(...) {
	RA_Calculations("PHPH", ...)
}

make_HarvestDataForPILI <- function(...){
	filterBySpecies("PILI", ...)
}

CalculateInvestmentForPILI <- function(...) {
	CalculateInvestmentForSpecies("PILI", ...)
}

CalculateAccesoryCostsForPILI <- function(...) {
	IAT_Species("PILI", ...)
}

CalculateRAForPILI <- function(...) {
	RA_Calculations("PILI", ...)
}

make_HarvestDataForPUTU <- function(...){
	filterBySpecies("PUTU", ...)
}

CalculateInvestmentForPUTU <- function(...) {
	CalculateInvestmentForSpecies("PUTU", ...)
}

CalculateAccesoryCostsForPUTU <- function(...) {
	IAT_Species("PUTU", ...)
}

CalculateRAForPUTU <- function(...) {
	RA_Calculations("PUTU", ...)
}


